version: "3.8"
services:
  database_mysql:
    container_name: db-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: film_db
    volumes:
      - my_db:/var/lib/mysql
      - ${PWD}/schema.sql:/docker-entrypoint-initdb.d/set.sql
    restart: always
    networks:
      - film_network
  film_service:
    container_name: film-service
    build: ./film-service
    environment:
      MYSQL_DATABASE: film_db
      CONTAINER_NAME_DATABASE: db-mysql
      MYSQL_PASSWORD: password123
      MYSQL_USER: user
    ports:
      - "8080:8080"
    networks:
      - film_network
    depends_on:
      - database_mysql
  review_service:
    container_name: review-service
    build:
      context: ./
      dockerfile: ./review-service/Dockerfile
    volumes:
      - ${PWD}/reviews.csv:/app/reviews.csv
    networks:
      - film_network
    depends_on:
      - film_service

volumes:
  my_db:
networks:
  film_network: